// Writes dist/sw.js: precaches every built file so the PWA works fully
// offline. The cache name is a hash of the file contents, so each deploy
// installs a fresh cache and deletes the old one.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname;
const files = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
};
walk(dist);
const skip = new Set(['sw.js', 'CNAME', '404.html']);
const urls = files.map((f) => relative(dist, f).split('\\').join('/')).filter((f) => !skip.has(f)).sort();
const hash = createHash('sha256');
for (const u of urls) hash.update(u).update(readFileSync(join(dist, u)));
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs
const CACHE = 'eehl-${version}';
const FILES = ${JSON.stringify(['./', ...urls.filter((u) => u !== 'index.html')], null, 0)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('eehl-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('./', { cacheName: CACHE }).then((r) => r || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((r) => r || fetch(req)));
});

self.addEventListener('notificationclick', (e) => {
  e.notification.close();
  e.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
      for (const c of list) if ('focus' in c) return c.focus();
      return self.clients.openWindow('./');
    }),
  );
});
`;
writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files, cache eehl-${version}`);
