// Generates src/core/lunar-data.ts from ICU (via Node's Intl), for the
// Korean (dangi) and Chinese lunisolar calendars.
//
// The app never asks the runtime's ICU for lunar dates: WebViews and browsers
// ship different ICU versions, and the counting engine must give the same
// answer everywhere. Instead we freeze ICU's answer into a small table here,
// and unit tests pin known dates (e.g. 2017: Korea 윤5월, China 闰六月).
//
// Run: npm run gen:lunar
import { writeFileSync } from 'node:fs';

const FIRST = 1900;
const LAST = 2100;
const DAY = 86400000;

function build(calendar) {
  const fmt = new Intl.DateTimeFormat('en-u-ca-' + calendar, {
    year: 'numeric', month: 'numeric', day: 'numeric', timeZone: 'UTC',
  });
  // Walk every day and record the first day of each lunar month.
  const starts = []; // { year, month, leap, day }
  const from = Date.UTC(FIRST - 1, 11, 1) / DAY;
  const to = Date.UTC(LAST + 2, 2, 1) / DAY;
  for (let d = from; d <= to; d++) {
    const parts = fmt.formatToParts(new Date(d * DAY));
    const get = (t) => parts.find((p) => p.type === t)?.value;
    const day = Number(get('day'));
    if (day !== 1) continue;
    const m = get('month');
    starts.push({ year: Number(get('relatedYear')), month: parseInt(m, 10), leap: /bis/.test(m), day: d });
  }
  const years = [];
  for (let y = FIRST; y <= LAST; y++) {
    const months = starts.filter((s) => s.year === y);
    const idx = starts.indexOf(months[0]);
    if (months.length < 12 || months[0].month !== 1 || months[0].leap) throw new Error(`bad year ${y}`);
    let leap = 0;
    let bits = 0;
    months.forEach((s, i) => {
      if (s.leap) leap = s.month;
      const len = starts[idx + i + 1].day - s.day;
      if (len !== 29 && len !== 30) throw new Error(`bad month length ${y}/${s.month}: ${len}`);
      if (len === 30) bits |= 1 << i;
    });
    if (months.length !== (leap ? 13 : 12)) throw new Error(`bad month count ${y}`);
    years.push([months[0].day, leap, bits]);
  }
  return years;
}

const out = `// GENERATED by scripts/gen-lunar.mjs from ICU ${process.versions.icu}. Do not edit.
// Per lunar year from ${FIRST}: [day number of 1/1 (days since 1970-01-01), leap month (0 = none),
// month-length bits (bit i set = i-th month of the year, leap included, has 30 days)].
export const LUNAR_FIRST_YEAR = ${FIRST};
export const LUNAR_LAST_YEAR = ${LAST};
export const DANGI: ReadonlyArray<readonly [number, number, number]> = ${JSON.stringify(build('dangi'))};
export const CHINESE: ReadonlyArray<readonly [number, number, number]> = ${JSON.stringify(build('chinese'))};
`;
writeFileSync(new URL('../src/core/lunar-data.ts', import.meta.url), out);
console.log('wrote src/core/lunar-data.ts');
