#!/usr/bin/env python3
# Generates src/core/solarterm-data.ts and spec/solar-terms.json: the UTC
# instants of the 24 solar terms (절기 / 节气 / 節気) for 1900–2100.
#
# A solar term is the instant the Sun's apparent geocentric ecliptic longitude
# (true equinox and ecliptic of date: precession, nutation and aberration
# included) reaches a multiple of 15°. PyEphem (libastro, VSOP87) supplies the
# apparent position and handles ΔT (its times are UT). Its solar longitude is
# good to about an arcsecond, i.e. ~25 s of time, so minute precision holds.
#
# Like the lunar tables, the app never computes astronomy at runtime: the
# answer is frozen here so every platform agrees.
#
# Dev-only. Run: pip install ephem && python3 scripts/gen-solar-terms.py
import json
import math
import os

import ephem

FIRST = 1900
LAST = 2100
# Calendar order within a Gregorian year, starting at 소한/小寒 (285°, ~Jan 5).
FIRST_LONGITUDE = 285
TROPICAL_YEAR = 365.24219
UNIX_EPOCH = float(ephem.Date('1970/1/1 00:00:00'))  # in ephem days (Dublin JD)


def apparent_longitude(t: float) -> float:
    """Apparent geocentric ecliptic longitude of the Sun (degrees, of date) at ephem date t (UT)."""
    sun = ephem.Sun()
    sun.compute(ephem.Date(t))
    # g_ra/g_dec are apparent geocentric coordinates for the epoch of date;
    # convert them on the ecliptic of the same epoch.
    eq = ephem.Equatorial(sun.g_ra, sun.g_dec, epoch=ephem.Date(t))
    return math.degrees(float(ephem.Ecliptic(eq).lon)) % 360.0


def diff(t: float, target: float) -> float:
    """Signed longitude difference lon(t) − target, wrapped into (−180, 180]."""
    d = (apparent_longitude(t) - target) % 360.0
    return d - 360.0 if d > 180.0 else d


def solve(target: float, guess: float) -> float:
    """Instant (ephem date) when the longitude equals target, near guess."""
    rate = 360.0 / TROPICAL_YEAR  # degrees per day, close enough for Newton steps
    t = guess
    for _ in range(50):
        step = diff(t, target) / rate
        t -= step
        if abs(step) < 1e-7:  # ~0.01 s
            break
    # Polish with bisection on a ±1 minute bracket to be safe against the
    # rate approximation (the Sun's speed varies ±3% over the year).
    lo, hi = t - 1 / 1440, t + 1 / 1440
    if diff(lo, target) < 0 < diff(hi, target):
        for _ in range(40):
            mid = (lo + hi) / 2
            if diff(mid, target) < 0:
                lo = mid
            else:
                hi = mid
        t = (lo + hi) / 2
    else:
        raise RuntimeError(f'bracket failed for {target} near {ephem.Date(guess)}')
    return t


def year_terms(year: int) -> list[int]:
    jan1 = float(ephem.Date(f'{year}/1/1 00:00:00'))
    out = []
    for k in range(24):
        target = (FIRST_LONGITUDE + 15 * k) % 360
        guess = jan1 + 5.5 + k * TROPICAL_YEAR / 24
        t = solve(target, guess)
        minutes = round((t - jan1) * 1440)
        if out and minutes <= out[-1]:
            raise RuntimeError(f'out of order in {year}')
        out.append(minutes)
    if out[0] < 0 or out[-1] >= 366 * 1440:
        raise RuntimeError(f'term outside year {year}')
    return out


def main() -> None:
    years = [year_terms(y) for y in range(FIRST, LAST + 1)]
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    rows = ',\n'.join('  [' + ','.join(str(m) for m in row) + ']' for row in years)
    ts = f"""// GENERATED by scripts/gen-solar-terms.py with PyEphem {ephem.__version__}. Do not edit.
// Per Gregorian year from {FIRST}: the 24 solar terms as minutes since that year's
// Jan 1 00:00 UTC, in time order starting with 소한/小寒 (apparent solar longitude
// {FIRST_LONGITUDE}°) and stepping 15° each (index 23 = 동지/冬至, 270°).
export const SOLAR_TERMS_FIRST_YEAR = {FIRST};
export const SOLAR_TERMS_LAST_YEAR = {LAST};
export const SOLAR_TERM_MINUTES: ReadonlyArray<ReadonlyArray<number>> = [
{rows},
];
"""
    with open(os.path.join(root, 'src/core/solarterm-data.ts'), 'w', encoding='utf-8') as f:
        f.write(ts)
    spec = {
        'generator': f'scripts/gen-solar-terms.py (PyEphem {ephem.__version__})',
        'firstYear': FIRST,
        'lastYear': LAST,
        'format': (
            'years[i] = the 24 solar terms of Gregorian year firstYear+i, as minutes since that year\'s '
            'Jan 1 00:00 UTC (rounded to the nearest minute), in time order. Index k is the instant the '
            f'Sun\'s apparent geocentric ecliptic longitude reaches ({FIRST_LONGITUDE} + 15k) mod 360 degrees: '
            '0 = minor cold (285°), 5 = spring equinox (0°), 11 = summer solstice (90°), '
            '17 = autumn equinox (180°), 23 = winter solstice (270°).'
        ),
        'years': years,
    }
    with open(os.path.join(root, 'spec/solar-terms.json'), 'w', encoding='utf-8') as f:
        f.write(json.dumps(spec, separators=(',', ':'), ensure_ascii=False) + '\n')
    print('wrote src/core/solarterm-data.ts and spec/solar-terms.json')


if __name__ == '__main__':
    main()
